In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Load the Iris dataset
iris = datasets.load_iris()

x = iris.data  # Features
y = iris.target  # Labels (species)

In [5]:
# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Initialize the k-NN classifier
knn = KNeighborsClassifier(n_neighbors = 3)

# Fit the model on the training data
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [6]:
# Make predictions on the testing data
y_pred_knn = knn.predict(x_test)

In [7]:
# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
class_report_knn = classification_report(y_test, y_pred_knn)

# Print the evaluation metrics
print(f"Accuracy: {accuracy_knn:.2f}")
print("Confusion Matrix:")
print(conf_matrix_knn)
print("k-NN Classification Report:", class_report_knn)

Accuracy: 1.00
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
k-NN Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [10]:
# Optional: Visualize the results
plt.figure(figsize=(8, 6))
plt.scatter(x_test[:, 0], x_test[:, 1], c = y_pred_knn, cmap='viridis', edgecolor='k', s=100)
plt.title("Iris Species Classification using K-NN")
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.show()